name: muslimate_mobile_app
description: "Your ultimate muslim companion"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0
workspace:
  # Register for melos needs
  # Register data layer
  - packages/data/data_common
  - packages/data/data_auth
  # Register domain layer
  - packages/domain/domain_common
  - packages/domain/domain_auth
  # Register presentation layer
  - packages/presentation/feature_common
  - packages/presentation/feature_auth
  - packages/presentation/feature_home
  - packages/presentation/feature_settings
  - packages/presentation/feature_qibla
  # Register shared library
  - packages/library/core
  - packages/library/uikit

dependencies:
  flutter:
    sdk: flutter
  # Register data layer as a package
  data_common:
    path: packages/data/data_common
  data_auth:
    path: packages/data/data_auth
  # Register domain layer as a package
  domain_common:
    path: packages/domain/domain_common
  domain_auth:
    path: packages/domain/domain_auth
  # Register presentation layer as a package
  feature_common:
    path: packages/presentation/feature_common
  feature_auth:
    path: packages/presentation/feature_auth
  feature_home:
    path: packages/presentation/feature_home
  feature_settings:
    path: packages/presentation/feature_settings
  feature_qibla:
    path: packages/presentation/feature_qibla
  # Register shared library as a package
  core:
    path: packages/library/core
  uikit:
    path: packages/library/uikit

  # Another library (third party)
  cupertino_icons: ^1.0.8
  injectable: ^2.5.1
  get_it: ^8.2.0
  go_router: ^16.2.1
  firebase_core: ^4.1.1
  firebase_crashlytics: ^5.0.2
  firebase_analytics: ^12.0.2
  firebase_remote_config: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  melos: ^7.1.1
  build_runner: 2.7.1
  freezed: ^3.2.3
  injectable_generator: ^2.8.1

melos:
  useRootAsPackage: true
  scripts:
    locale:
      run: cd packages/library/uikit && flutter gen-l10n
      description: Running flutter gen-l10n in uikit package.
    assets:
      run: cd packages/library/uikit && dart run build_runner build
      description: Running flutter_gen in uikit package.
    build:
      run: melos exec "dart run build_runner build -d"
      description: Generate runner based on selected module
      packageFilters:
        flutter: true

flutter:
  uses-material-design: true
