targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/src/model/**
      injectable_generator:injectable_builder:
        generate_for:
          include:
            - lib/src/use_case/**
            - lib/src/di/di.dart