name: domain_auth
resolution: workspace
description: "domain_auth layer"
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  injectable: ^2.5.1
  get_it: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: 2.7.1
  injectable_generator: ^2.8.1

flutter:
