// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZFu2nvKZ7aLK_k-3ciEun_hqZ2hxAEGo',
    appId: '1:154261225149:web:b7a791726132138c3f01d4',
    messagingSenderId: '154261225149',
    projectId: 'muslimate-app-6ae3f',
    authDomain: 'muslimate-app-6ae3f.firebaseapp.com',
    storageBucket: 'muslimate-app-6ae3f.firebasestorage.app',
    measurementId: 'G-7QP0G8Y5ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1-380Jny6YRKYw9NhxacEwD2VZAs42aQ',
    appId: '1:154261225149:android:4be4f2ba1214bb0b3f01d4',
    messagingSenderId: '154261225149',
    projectId: 'muslimate-app-6ae3f',
    storageBucket: 'muslimate-app-6ae3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTZyBbd5VO2a3O8AslhA8VP-ZGC-WoPWs',
    appId: '1:154261225149:ios:6f11a2232a8549b23f01d4',
    messagingSenderId: '154261225149',
    projectId: 'muslimate-app-6ae3f',
    storageBucket: 'muslimate-app-6ae3f.firebasestorage.app',
    iosBundleId: 'com.ngoprekcode.muslimate',
  );
}
