targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/failure/**
      injectable_generator:injectable_builder:
        generate_for:
          include:
            - lib/local/**
            - lib/di/di.dart