name: feature_qibla
resolution: workspace
description: "feature_qibla layer"
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  uikit:
    path: ../../library/uikit
  freezed_annotation: ^3.1.0
  flutter_bloc: ^9.1.1
  injectable: ^2.5.1
  get_it: ^8.2.0
  go_router: ^16.2.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  flutter_compass: ^0.8.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: 2.7.1
  injectable_generator: ^2.8.1
  freezed: ^3.2.3

flutter:
