name: feature_settings
resolution: workspace
description: "feature_settings layer"
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  uikit:
    path: ../../library/uikit
  freezed_annotation: ^3.1.0
  flutter_bloc: ^9.1.1
  injectable: ^2.5.1
  get_it: ^8.2.0
  go_router: ^16.2.1
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: 2.7.1
  injectable_generator: ^2.8.1
  freezed: ^3.2.3

flutter:
